version: "3.9"
services:
  pg:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: dev-directory
